### ISSUE TITLE
Remove health endpoint for Liberty 

### ISSUE THREAD

**Issue by Emily-Jiang** [ibm-developer/generator-ibm-java#110]
https://github.com/ibm-developer/generator-ibm-java/blob/master/generator-java/generators/app/templates/blank/liberty/src/main/java/application/HealthEndpoint.java

The above file should be removed as Liberty has the mpHealth-1.0 directly exposes the /heath endpoint.

**Comment by jkingoliver** [comment]
@Emily-Jiang will you propose the necessary change in a PR here?
